name: Build AutoCAD Plugin

on: [push, pull_request]

jobs:
  build:
    # MUST use Windows for WinForms and Autodesk libraries
    runs-on: windows-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.8.x' # Sử dụng SDK .NET 6

    - name: Build
      run: dotnet build MyApp.csproj -c Release
    
    - name: Test
      run: |
        dotnet test --no-build -c Release

        dir bin
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AutoCAD-Plugin-DLL
        path: bin/Release/net*/ # Uploads the compiled .dll
